### ISSUE TITLE
 Questions about FID

### ISSUE THREAD

**Issue by sunovivid** [placerkyo/BSRD#2]
Hi. I have read the paper and I believe it is an interesting and important research direction😊

I have a question regarding the content of the paper: how did you measure FID? 
The basic evaluations only measure PSNR, SSIM, and LPIPS, so I would like to know how to measure FID. 

It seems that there is an FID evaluator from OpenAI ADM in `evaluations/evaluator.py`, but I'm not sure which reference batch should be used. Could you provide the `.npz` file or the code to create the reference batch used for measuring FID?

Thank you!!

**Comment by placerkyo** [comment]
Thank you for being so interested in our paper.
You can generate a .npz file of gt by using the ```save_npz``` function in sample_synth.py.
As in line 195 of sample_synth.py, which generates the .npz of the prediction, you may generate it by ```save_npz(all_images_gt, "gt", "")```.

**Comment by sunovivid** [comment]
Thank you for your kind and quick response! It helped a lot.
